build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:latest
  amd64: ghcr.io/hassio-addons/base/amd64:latest
  armhf: ghcr.io/hassio-addons/base/armhf:latest
  armv7: ghcr.io/hassio-addons/base/armv7:latest
  i386: ghcr.io/hassio-addons/base/i386:latest
labels:
  io.hass.name: "Llamafile"
  io.hass.description: "Run language models locally with llamafile"
  io.hass.role: "addon"
  io.hass.type: "addon"
  io.hass.version: "1.0.0" 